mysite/accountpage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("orderspage", views.AccountpageView.as_view(), name="orderspage"),
    path("orderspage/outstanding/pay/<slug:payment_method_slug>/<slug:invoice_slug>", views.OrderprocessingpageView.as_view(), name="orderprocessingpage"),
    path("orderspage/outstanding/view/<slug:invoice_slug>", views.OutstandingpageView.as_view(), name="outstandingpage"),
    path("orderspage/paid/view/<slug:invoice_slug>", views.PaidpageView.as_view(), name="paidpage"),
    path("orderspage/paid/remarks/<slug:invoice_slug>", views.RemarkspageView.as_view(), name="remarkspage"),
    path("orderspage/complete/view/<slug:invoice_slug>", views.CompletepageView.as_view(), name="completepage"),
    path("orderspage/outstanding/promo/<slug:invoice_slug>", views.PromocodepageView.as_view(), name="promocodepage"),
    path("orderspage/outstanding/stripeaccepted/<slug:invoice_slug>", views.StripereturnpageView.as_view(), name="stripereturnpage"),
    path("orderspage/outstanding/pay/invalid", views.InvalidpageView.as_view(), name="invalidpage"),
    path("messengerpage", views.MessengerpageView.as_view(), name="messengerpage"),
    path("addmessage", views.Addmessagepage.as_view(), name="addmessagepage"),
    #path("messengerpage/title/<slug:inquiry_ref_slug>", views.MessengertitlepageView.as_view(), name="messengertitlepage"),
    path("messengerpage/messages/<slug:inquiry_ref_slug>", views.MessengermessagespageView.as_view(), name="messengermessagespage"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('accounts/', include('django.contrib.auth.urls')),
                #   path('admin/', admin.site.urls),
                  path("", include("homepage.urls")),
                  path("homepage/", include("homepage.urls")),
                  path("lang/", include("homepage.urls")),
                  path("products/", include("productspage.urls")),
                  path("authenpage/", include("authenpage.urls")),
                  path("cartpage/", include("cartpage.urls")),
                  path("accountpage/", include("accountpage.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/accountpage/models.py
import datetime
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.core.files import File
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO
from django.conf import settings
from os import remove
from django.utils import timezone
from datetime import datetime

# Create your models here.


class Messages(models.Model):
    GOAL_TYPE = (
        ('comment', 'comment'),
        ('surrogate', 'surrogate shopping'),
        ('product_info', 'about our products'),
        ('exchange', 'items exchange'),
        ('refund', 'refund'),
        ('cancel', 'cancel'),
        ('return', 'returning items'),
        ('complaint', 'complaint'),
        ('other', 'other inquiry'),
        ('reply', 'reply'),
    )

    username = models.CharField(default="", max_length=300)
    inquiry_ref = models.CharField(default="", max_length=400, db_index=True, blank=True)
    slug = models.SlugField(max_length=300, blank=True, db_index=True)
    title = models.CharField(default="", max_length=300, help_text="300 characters less", db_index=True)
    title_check = models.BooleanField(default=False)
    goal = models.CharField(max_length=100, choices=GOAL_TYPE, default="inquiry", db_index=True)
    message = models.TextField(default="", max_length="2000", help_text="2000 characters less")
    user_created = models.BooleanField(default=True)
    reply = models.BooleanField(default=False)
    close = models.BooleanField(default=False)
    created_at = models.DateTimeField("date of creation", auto_now_add=True)

    class Meta:
        ordering = ('username',)
        index_together = (('id', 'slug'),)
        verbose_name = 'messages'
        verbose_name_plural = 'messages'

    def __str__(self):
        return self.username

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def save(self, *args, **kwargs):
        if self.user_created == True:
            if self.inquiry_ref == "":
                self.created_at = datetime.now()
                time = datetime.strftime(self.created_at, "%y%j%H%M%S")
                name = self.username
                self.inquiry_ref = name + time
                self.created_at = datetime.now()

            if self.title_check == False:
                title = self.title
                self.title = title + " ' " + time + " ' "
                self.title_check = True


            super(Messages, self).save(*args, **kwargs)


mysite/cartpage/models.py
import datetime, os
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.core.files import File
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO
from django.conf import settings
from os import remove


class Invoice(models.Model):

    PAYMENT_METHOD = (
        ('O', 'CreditCards'),
        ('T', 'BankTransfer'),
    )

    DELIVERY_METHOD = (
        ('PU', 'PickUpAtStore'),
        ('DL', 'Delivery'),
    )

    DELIVERY_STATUS = (
        ('W', 'Waiting for the payment'),
        ('A', 'upload received'),
        ('P', 'Preparing'),
        ('D', 'Dispatched'),
        ('R', 'Ready to collect'),
        ('C', 'Collected')
    )

    invoice = models.CharField(max_length=250, blank=True, help_text="(updated on save)", db_index=True)
    slug = models.SlugField(max_length=100, blank=True, db_index=True)
    username = models.CharField(max_length=125, blank=False, help_text="(updated on save)")
    first_name = models.CharField(max_length=125, blank=False, help_text="Receiver's first name")
    last_name = models.CharField(max_length=125, blank=True, help_text="Receiver's last name")
    payment_method = models.CharField(max_length=100, choices=PAYMENT_METHOD, default="both", db_index=True)
    delivery_method = models.CharField(max_length=100, choices=DELIVERY_METHOD, default="both", db_index=True)
    total_amount = models.IntegerField(blank=True, help_text="(updated on save)")
    total_cost = models.IntegerField(blank=True, help_text="(updated on save)")
    phone_no = models.CharField(max_length=100, blank=True, help_text="(updated on save)")
    address = models.TextField(default="Pick up at store")
    remarks = models.CharField(max_length=125, blank=True, default="")
    remarks_unread = models.BooleanField(default=False)
    promo = models.BooleanField(default=False)
    promo_code = models.CharField(max_length=125, blank=True, help_text="(updated on save)")
    ori_total_amount = models.IntegerField(default="", blank=True)

    outstanding = models.BooleanField(default=True)
    delivery_status = models.CharField(max_length=100, choices=DELIVERY_STATUS, default="P")
    advice_slip = models.BooleanField(default=False)
    advice_slip_file = models.ImageField(upload_to='myshop/invoice/%Y%m%d', blank=True,)
    ready = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)
    cancel = models.BooleanField(default=False)
    refund = models.BooleanField(default=False)

    created_at = models.DateTimeField("date of creation", auto_now_add=True)
    eta = models.CharField(max_length=50, blank=True, default="")
    check_outstanding = models.BooleanField(default=False)
    invoice_file = models.FileField(upload_to='invoices/%Y%m%d', blank=True)
    printed = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.invoice == "":
            self.created_at = datetime.now()
            time = datetime.strftime(self.created_at, "%Y%m%d%H%M%S")
            self.invoice = self.username + str(time) + self.payment_method + str(self.total_amount) + self.first_name[0] + self.last_name[0]
            self.slug = self.invoice
            super(Invoice, self).save(*args, **kwargs)
        else:
            if self.outstanding == False and self.check_outstanding == False:
                self.check_outstanding = True
                time= datetime.now()
                time_invoice = datetime.strftime(time, "%d/%m/%Y @%H:%M")
                #595*842
                canvas1 = canvas.Canvas(os.path.join(settings.MEDIA_ROOT, str(self.invoice + ".pdf")))
                canvas1.setLineWidth(.3)
                canvas1.setFont('Helvetica', 18)
                canvas1.drawCentredString(298, 760, "OFFICIAL INNVOICE OF HIMONA")
                canvas1.line(30, 740, 565, 740)

                canvas1.setFont('Helvetica', 12)
                canvas1.drawString(30, 710, "INVOICE No.: " + str(self.invoice))
                canvas1.drawString(380, 710, "PAYMENT VIA: " + str(self.payment_method))
                canvas1.drawString(30, 680, "ORDERED BY: " + str(self.username))
                canvas1.drawString(380, 680, "DELIVERY TO: " + str(self.delivery_method))

                canvas1.drawString(30, 650, "PRODUCT ID")
                canvas1.drawString(230, 650, "SELLING PRICE/UNIT $")
                canvas1.drawString(380, 650, "QUANTITY")
                canvas1.drawString(460, 650, "TOTAL PRICE ($)")
                canvas1.drawString(30, 620, "ADDRESS: " + str(self.address))
                canvas1.line(30, 610, 565, 610)
                canvas1.line(30, 607, 565, 607)

                height = 620
                line = 610
                interval = 40

                items = InvoiceDetails.objects.filter(details_invoice__invoice=self.invoice)
                canvas1.setFont('Helvetica', 12)
                counter_page = 7
                page = 1
                canvas1.drawCentredString(298, 30, str("Page" + str(page)))
                for i in items:
                    stop = False
                    counter_page = counter_page - 1
                    if counter_page == -1:
                        page = page + 1
                        canvas1.showPage()
                        canvas1.drawCentredString(298, 760, "OFFICIAL INNVOICE OF HIMONA")
                        canvas1.line(30, 740, 565, 740)

                        canvas1.setFont('Helvetica', 12)
                        canvas1.drawString(30, 710, "INVOICE No.: " + str(self.invoice))
                        canvas1.drawString(380, 710, "PAYMENT VIA: " + str(self.payment_method))
                        canvas1.drawString(30, 680, "ORDERED BY: " + str(self.username))
                        canvas1.drawString(380, 680, "DELIVERY TO: " + str(self.delivery_method))

                        canvas1.drawString(30, 650, "PRODUCT ID")
                        canvas1.drawString(230, 650, "SELLING PRICE/UNIT $")
                        canvas1.drawString(380, 650, "QUANTITY")
                        canvas1.drawString(460, 650, "TOTAL PRICE ($)")
                        canvas1.drawString(30, 620, "ADDRESS: " + str(self.address))
                        canvas1.line(30, 610, 565, 610)
                        canvas1.line(30, 607, 565, 607)

                        height = 620
                        line = 610
                        interval = 40

                        canvas1.setFont('Helvetica', 12)
                        counter_page = 7
                        stop = True
                        canvas1.drawCentredString(298, 30, str("Page" + str(page)))
                        canvas1.drawString(30, (height - interval), i.product_id_unique)
                        canvas1.drawString(230, (height - interval), str(i.selling_price))
                        canvas1.drawString(380, (height - interval), str(i.quantity))
                        canvas1.drawString(460, (height - interval), str(i.selling_price * i.quantity))
                        if i.preorder == True:
                            canvas1.drawString(530, (height - interval), str("Pre"))

                        height = height - interval
                        line = line - interval
                    else:
                        stop = True
                        canvas1.drawString(30, (height - interval), i.product_id_unique)
                        canvas1.drawString(230, (height - interval), str(i.selling_price))
                        canvas1.drawString(380, (height - interval), str(i.quantity))
                        canvas1.drawString(460, (height - interval), str(i.selling_price * i.quantity))
                        if i.preorder == True:
                            canvas1.drawString(530, (height - interval), str("Pre"))

                        height = height - interval
                        line = line - interval


                canvas1.drawCentredString(298, (line-5), "--------------------------------------------------------------------------------------------------------------------------------------")
                #canvas1.line(30, (line), 565, (line))
                canvas1.drawString(380, (height - interval), "TOTAL $: ")
                canvas1.drawString(460, (height - interval), str(self.total_amount))
                canvas1.drawString(30, (height - interval), str("SETTLED ON: " + time_invoice))
                height = height - interval - interval
                line = line - interval - interval
                canvas1.drawString(30, (height - interval), str("RECEIVED BY: ______________________"))
                canvas1.drawString(380, (height - interval), str("RECEIVED ON: ______________"))
                height = height - interval
                line = line - interval
                canvas1.drawString(30, (height - interval), str("(NAME & SIGNATURE)"))
                height = height - interval
                line = line - interval
                canvas1.line(30, (line), 565, (line))
                canvas1.line(30, (line-3), 565, (line-3))
                canvas1.drawCentredString(298, (height - interval), "END OF INVOICE")
                canvas1.save()


                #file = open(str(self.invoice + ".pdf"), "rb")
                file = open(os.path.join(settings.MEDIA_ROOT, str(self.invoice + ".pdf")), 'rb+')
                self.invoice_file.save(str(self.invoice + ".pdf"), file)
                #self.invoice_file.save(os.path.join(settings.MEDIA_ROOT, str(self.invoice + ".pdf")), file)
                file.close()
                #remove(str(self.invoice + ".pdf"))
                remove(os.path.join(settings.MEDIA_ROOT, str(self.invoice + ".pdf")))

mysite/accountpage/forms.py
from django.forms import ModelForm
import sys
sys.path.append('../')
from cartpage.models import Invoice, InvoiceDetails, PromoCode
from .models import Messages
from django import forms


class InvoiceAdviceSlip(ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'advice_slip_file',
            'invoice',
            'advice_slip',
            'delivery_status',
        ]


class Remarks(ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'invoice',
            'remarks',
            'remarks_unread',
        ]


class OutstandingDetailForm(ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'invoice',
            'payment_method',
            'delivery_method',
            'address',
            'cancel',
        ]


class PromoCodeApplyForm(ModelForm):
    class Meta:
        model = PromoCode
        fields = [
            'promo_code',
        ]


class AddMessageForm(ModelForm):
    class Meta:
        model = Messages
        fields = [
            'username',
            'title',
            'goal',
            'message',
        ]

mysite/templates/accountpage/addmessagepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HIMONA</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
<br>
<form method="post" class="form-signin" action="">
    {% csrf_token %}
    <table align="center">
        <thead>
        <tr>
            <td>
                {% if request.session.lang == 'chi' %}
                <h3>填寫您的留言或查詢:</h3>
                {% else %}
                <h3>Please leave your comment here:</h3>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td><br></td>
        </tr>
        </thead>
        {% for field in form %}
        <tr><td><br></td></tr>
        {% if 'Username:' in field.label_tag %}
        <input type="text" name="username" value="{{ username }}" hidden>
        {% elif 'Goal:' in field.label_tag %}
        {% if request.session.lang == 'chi' %}
        <tr>
            <td align="center|justify">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing" style="width: 120px;">類型:</span>
                    </div>
                    <select class="costom-select" name="goal" size="1">
                        {% for a, b in goal_list %}
                        <option value="{{a}}">{{b}}</option>
                        {% endfor %}
                    </select>
                </div>
                {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                <p align="center" style="color: red">{{ error }}</p>
                {% endfor %}
            </td>
        </tr>
        {% else %}
        <tr>
            <td align="center|justify">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing" style="width: 120px;">Inquiry type:</span>
                    </div>
                    <select class="costom-select" name="goal" size="1">
                        {% for a, b in goal_list_eng %}
                        <option value="{{a}}">{{b}}</option>
                        {% endfor %}
                    </select>
                </div>
                {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                <p align="center" style="color: red">{{ error }}</p>
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        {% else %}
        <tr>
            <td align="center|justify">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing" style="width: 120px;">{{ field.label_tag }}</span>
                    </div>
                    {{ field }}
                </div>
                {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                <p align="center" style="color: red">{{ error }}</p>
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <tr>
            <td>
                <br>
                <script src='https://www.google.com/recaptcha/api.js'></script>
                <div class="g-recaptcha" data-sitekey="6Lfv46cUAAAAAItYVa7ZIYJVi-GuPNEwxPtHqMFQ"></div>
            </td>
        </tr>
        <tr>
            <td align="center">
                <br>
                <input class="btn btn-primary" type="submit" value="留言">
            </td>
        </tr>
    </table>
</form>
{% endblock%}
</body>
</html>

mysite/templates/accountpage/checkouttest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HIMONA</title>
</head>
<body>
<script src="https://js.stripe.com/v3/"></script>
<script>
    var stripe = Stripe('pk_test_GbOuQ9RVpbLxVyLPhK486dPh009yJMdVNl');
    stripe.redirectToCheckout({
  sessionId: '{{payment_id}}'
}).then(function (result) {
  // If `redirectToCheckout` fails due to a browser or network
  // error, display the localized error message to your customer
  // using `result.error.message`.
});
</script>
</body>
</html>

mysite/templates/accountpage/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HIMONA</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
<style>
    textarea {
    height: 50px;
}
</style>
{% if request.session.lang == "chi" %}
<main style="margin-right: 25px; margin-left: 25px;">
    <hr>
    <br>
    <h3 align="center">Order Ref: <span style="color:auto;">{{invoice_slug}}</span></h3>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>
                物品編號.
            </th>
            <th>
                樣式
            </th>
            <th>
                款式
            </th>
            <th>
                尺碼
            </th>
            <th>
                每件價格
            </th>
            <th>
                數量
            </th>
            <th>
                狀態
            </th>
        </tr>
        </thead>
        <tbody>
        {% for i in invoice_detail_item %}
        <tr>
            <td>
                <h6>{{ i.product_id_unique }}</h6>
            </td>
            <td>
                {% for j in product_details %}
                {% if j.product_id_unique == i.product_id_unique %}
                <img class="" src="{{j.img1_thumbnail.url}}" alt="Card image cap" style="height: auto; width: 120PX; display: block;" data-holder-rendered="true">
                {% endif %}
                {% endfor %}
            </td>
            <td>
                <h6>{{ i.color }}</h6>
            </td>
            <td>
                <h6>{{ i.size }}</h6>
            </td>
            <td>
                <h6>${{ i.selling_price }}</h6>
            </td>
            <td>
                <h6>{{ i.quantity }}</h6>
            </td>
            <td>
                {% if i.preorder == False %}
                <h6 style="color:green;">存庫包裝中</h6>
                {% else %}
                <h6 style="color:red;">預購</h6>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <div class="row">
        <div class="col-6"align="left">
            <h5>Delivery method: [
                {% if invoice_item.delivery_method == "PU" %}
                到店自取
                {% else %}
                寄至: {{invoice_item.address}}
                {% endif %}
                ]
            </h5>
            <br>
            <h5 align="left">預計送達時間:
            </h5>
            <h5>[
                {% if invoice_item.eta == "" %}
                稍後更新
                {% else %}
                {{invoice_item.eta}}
                {% endif %}
                ]
            </h5>
        </div>
        <div class="col-6" align="right">
            <h4 align="right">總額: HKD ${{invoice_item.total_amount}} (已收取)</h4>
            <h5 align="right">
                優惠碼使用: [
                {% if invoice_item.promo == True %}
                {{invoice_item.promo_code}}
                {% else %}
                ----
                {% endif %}
                ]
            </h5>
            <h5 align="right">付款方法[
                {% if invoice_item.payment_method == "P" %}
                PayPal
                {% elif invoice_item.payment_method == "O" %}
                Credit card by Stripe
                {% else %}
                Bank transfer
                {% endif %}
                ]
            </h5>
            <br>
            <h5 align="right">下單時間: {{invoice_item.created_at}}</h5>
            <h6 align="right">訂單款額已收取. 謝謝惠顧</h6>
        </div>
    </div>
    <hr>
    <h6 align="center">---發票完---</h6>
</main>
{% else %}
<main style="margin-right: 25px; margin-left: 25px;">
    <hr>
    <br>
    <h3 align="center">Order Ref: <span style="color:auto;">{{invoice_slug}}</span></h3>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>
                Item No.
            </th>
            <th>
                Photo
            </th>
            <th>
                Color
            </th>
            <th>
                Size
            </th>
            <th>
                Unit Price
            </th>
            <th>
                Quantity
            </th>
            <th>
                Status
            </th>
        </tr>
        </thead>
        <tbody>
        {% for i in invoice_detail_item %}
        <tr>
            <td>
                <h6>{{ i.product_id_unique }}</h6>
            </td>
            <td>
                {% for j in product_details %}
                {% if j.product_id_unique == i.product_id_unique %}
                <img class="" src="{{j.img1_thumbnail.url}}" alt="Card image cap" style="height: auto; width: 120PX; display: block;" data-holder-rendered="true">
                {% endif %}
                {% endfor %}
            </td>
            <td>
                <h6>{{ i.color }}</h6>
            </td>
            <td>
                <h6>{{ i.size }}</h6>
            </td>
            <td>
                <h6>${{ i.selling_price }}</h6>
            </td>
            <td>
                <h6>{{ i.quantity }}</h6>
            </td>
            <td>
                {% if i.preorder == False %}
                <h6 style="color:green;">In stock and preparing</h6>
                {% else %}
                <h6 style="color:red;">Pre Order</h6>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <div class="row">
        <div class="col-6"align="left">
            <h5>Delivery method: [
                {% if invoice_item.delivery_method == "PU" %}
                Pick up at store
                {% else %}
                Deliver to: {{invoice_item.address}}
                {% endif %}
                ]
            </h5>
            <br>
            <h5 align="left">Estimated time of delivery:
            </h5>
            <h5>[
                {% if invoice_item.eta == "" %}
                Will be update ASAP
                {% else %}
                {{invoice_item.eta}}
                {% endif %}
                ]
            </h5>
        </div>
        <div class="col-6" align="right">
            <h4 align="right">Total amount: HKD ${{invoice_item.total_amount}} (received)</h4>
            <h5 align="right">
                Promo code: [
                {% if invoice_item.promo == True %}
                {{invoice_item.promo_code}}
                {% else %}
                ----
                {% endif %}
                ]
            </h5>
            <h5 align="right">Pay by: [
                {% if invoice_item.payment_method == "P" %}
                PayPal
                {% elif invoice_item.payment_method == "O" %}
                Credit card by Stripe
                {% else %}
                Bank transfer
                {% endif %}
                ]
            </h5>
            <br>
            <h5 align="right">Order created at: {{invoice_item.created_at}}</h5>
            <h6 align="right">Payment was accepted within 72 hours.</h6>
        </div>
    </div>
    <hr>
    <h6 align="center"> End of Invoice</h6>
</main>
{% endif %}
{% endblock %}
</body>
</html>

mysite/templates/accountpage/orderprocessingadviceslip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HIMONA</title>
</head>
<body>

{% extends "base.html" %}
{% block content %}
{% if request.session.site_language == "chi" %}
<main style="margin-right: 25px; margin-left: 25px;">
    <br><br>
    <h3 align="center">上傳你的入數紙.</h3>
    <hr>
    <div align="center"><h5>訂單編號. <span style="color:blue;">{{invoice_slug}}</span></h5></div>
    <br>
    <div align="center"><h5>總額: $<span style="color:blue;">{{total_amount}}</span></h5></div>
    <br>
    <form method="post" class="form-signin" action="" enctype='multipart/form-data'>
        {% csrf_token %}
        <input type="text" name="invoice" value="{{ invoice_slug }}" hidden>
        <input type="text" name="delivery_status" value="A" hidden>
        <input type="checkbox" name="advice_slip" value="True" checked hidden>
        <table align="center">
            <tr>
                <td>
                    <input id="id_advice_slip_file" type="file" name="advice_slip_file" accept="image/*" required/>
                </td>
            </tr>
            <tr>
                <td><br></td>
            </tr>
            <tr>
                <td>
                    <input class="btn btn-primary" type="submit" value="上傳">
                </td>
            </tr>
        </table>
    </form>
</main>
{% else %}
<main style="margin-right: 25px; margin-left: 25px;">
    <br><br>
    <h3 align="center">Please click Upload to upload your advice slip.</h3>
    <hr>
    <div align="center"><h5>Order No. <span style="color:blue;">{{invoice_slug}}</span></h5></div>
    <br>
    <div align="center"><h5>Total amount: $<span style="color:blue;">{{total_amount}}</span></h5></div>
    <br>
    <form method="post" class="form-signin" action="" enctype='multipart/form-data'>
        {% csrf_token %}
        <input type="text" name="invoice" value="{{ invoice_slug }}" hidden>
        <input type="text" name="delivery_status" value="A" hidden>
        <input type="checkbox" name="advice_slip" value="True" checked hidden>
        <table align="center">
            <tr>
                <td>
                    <input id="id_advice_slip_file" type="file" name="advice_slip_file" accept="image/*" required/>
                </td>
            </tr>
            <tr>
                <td><br></td>
            </tr>
            <tr>
                <td>
                    <input class="btn btn-primary" type="submit" value="Upload">
                </td>
            </tr>
        </table>
    </form>
</main>
{% endif %}
{% endblock %}
</body>
</html>